---
name: Docs
"on":
  push:
    # Only targets main branch to avoid amplification effects of auto-fixing
    # the exact same stuff in multiple non-rebased branches.
    branches:
      - main

jobs:

  docs:
    uses: kdeldycke/workflows/.github/workflows/docs.yaml@v3.1.0

  repo-sync:
    name: Import changes from template repository
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: AndreasAugustin/actions-template-sync@v1.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: kdeldycke/awesome-template
          pr_title: "[sync] Template repository updates"
          pr_commit_msg: "[sync] Template repository updates"
          # pr_labels: "ðŸ“š documentation"